name: omnireader
description: The ultimate reading companion for managing manga, manhwa, and manhua collections with advanced features and AI integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Dependencies
  cupertino_icons: ^1.0.6

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Database & Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0-beta.4

  # UI & Design
  flutter_staggered_grid_view: ^0.7.0
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.8
  lottie: ^3.3.0
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^4.0.0
  flutter_speed_dial: ^7.0.0
  badges: ^3.1.2

  # Navigation & Routing
  go_router: ^16.0.0

  # Networking & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  connectivity_plus: ^6.1.4

  # Image Handling
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.4.1
  image_picker: ^1.0.4
  image_cropper: ^9.1.0
  photo_view: ^0.15.0

  # Notifications
  flutter_local_notifications: ^19.4.0
  awesome_notifications: ^0.10.1
  workmanager: ^0.9.0

  # File & Media
  file_picker: ^10.2.1
  open_filex: ^4.3.4
  share_plus: ^11.0.0
  url_launcher: ^6.2.1

  # Utilities
  intl: ^0.20.2
  uuid: ^4.1.0
  crypto: ^3.0.3
  collection: ^1.18.0
  equatable: ^2.0.5
  path: ^1.9.1

  # Charts & Analytics
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.1.42

  # Authentication & Security
  local_auth: ^2.1.7
  flutter_keychain: ^2.3.0

  # Device Features
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.1
  vibration: ^3.1.3

  # Search & Filtering
  flutter_typeahead: ^5.2.0

  # Theme & Customization
  # flex_color_scheme: ^6.1.2
  google_fonts: ^6.1.0

  # Performance & Monitoring
  flutter_native_splash: ^2.3.6

  # AI & ML Integration
  http: ^1.1.0

  # Export & Import
  csv: ^6.0.0
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  retrofit_generator: ^9.2.0

  # Linting & Analysis
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0

  # Testing
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

  # Icons & Assets
  flutter_launcher_icons: ^0.14.4

  # Build Tools
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_logo.png
  color_dark: "#121212"
  image_dark: assets/images/splash_logo_dark.png
  android_12:
    image: assets/images/splash_logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/splash_logo_dark.png
    icon_background_color_dark: "#121212"
  web: false
